name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        compiler: [gcc, clang]

    steps:
      - uses: actions/checkout@v4

      - name: install-build-essentials
        run: |
          sudo apt-get update
          sudo apt-get install build-essential

      - name: install-meson-pip3
        run: |
          sudo apt-get install -y python3 python3-pip python3-setuptools \
          python3-wheel ninja-build
          pip3 install --user ninja meson
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: install-clang
        if: matrix.compiler == 'clang'
        run: sudo apt-get install -y clang

      - name: configure-build
        run: meson setup build
        env:
          CC: ${{ matrix.compiler }}

      - name: build
        run: meson compile -C build

      - name: test
        run: meson test -C build
